heat_template_version: 2016-10-14
description: Create a project
parameters:
  public_net_id:
    type: string
    description: The ID for the floating ip
  project_name:
    type: string
    description: Name of the project for the flavors
  project_guid: 
    type: string
  api_user:
    type: string
    default: ""
    description: User for API calls (i.e. ipmi)
  api_pass:
    type: string
    default: ""
    description: Password for API user
  api_url:
    type: string
    default: ""
    description: OSP URL for API calls
 
resources:
  openstack_project_infra_key:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: $project$-infra_key
          params:
             $project$: { get_param: project_guid }
      save_private_key: true
  Network0_network:
    type: OS::Neutron::Net
    properties:
      name: "Network0"
      shared: false
      value_specs: {"mtu": 1450}
  Network0_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network0"
      network_id: { get_resource: Network0_network }
      cidr: "10.0.100.0/24"
      gateway_ip: "10.0.100.1"
      enable_dhcp: "False"
      
      dns_nameservers:
      
        - 8.8.8.8
  Router0_router:
    type: OS::Neutron::Router
    properties:
      name: "Router0"
      external_gateway_info: { "network": { get_param: public_net_id } }

  
  Router0_Network0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      fixed_ips:
        - ip_address: "10.0.100.1"
  


  
  Router0_Network0_router_if:
    type: OS::Neutron::RouterInterface
    properties:
        router: { get_resource: Router0_router }
        port: { get_resource: Router0_Network0_port }
  
  client1.example.com_services_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: client1.example.com_services_sg
      rules:
      
      - {port_range_max: 10000, port_range_min: 10000, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 10.0.100.156/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 10.0.100.156/255.255.255.0}
      
  client1.example.com-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:06:e2:ed"
      
      security_groups:
        - client1.example.com_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "10.0.100.156"}
      
    
    depends_on:
      
      
      - client1.example.com_services_sg
      
    
  client1.example.com_volume_vol:
    type: OS::Cinder::Volume
    properties:
      name: "client1.example.com-vol"
      
      image: "Breakfix-booting-ARCHIVE-client1.example.com-vda"
      
      size: "10"
  client1.example.com_server:
    type: OS::Nova::Server
    properties:
      name: "client1.example.com"
      
      image: "Breakfix-booting-ARCHIVE-client1.example.com-sr0"
      
      config_drive: True
      #flavor: "CPU_2_Memory_16384_Disk_None"
      flavor: "quicklab.m1.medium"

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "RHEL 7.2 machine for kernel break fix"
        
        "hostname": 
          str_replace:
            template: "client1"
            params:
              REPL: {get_param: project_guid}
        
         
        "cdrom": "Breakfix-booting-ARCHIVE-client1.example.com-sr0"
         
        
      #personality: {"/etc/cloud/cloud.cfg.d/99-custom-networking.cfg": "network: {config: disabled}\n"}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: client1.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: client1.example.com-0_port}
        
      
      block_device_mapping_v2:
        
        - volume_id: { get_resource: client1.example.com_volume_vol }
          boot_index: 1
        
      
    

  

outputs:
  openstack_project_infra_key:
    description: The SSH infra key
    value: {get_attr: [openstack_project_infra_key, private_key]}

