heat_template_version: 2016-10-14
description: Create a project
parameters:
  public_net_id:
    type: string
    description: The ID for the floating ip
  project_name:
    type: string
    description: Name of the project for the flavors
  project_guid: 
    type: string
  api_user:
    type: string
    default: ""
    description: User for API calls (i.e. ipmi)
  api_pass:
    type: string
    default: ""
    description: Password for API user
  api_url:
    type: string
    default: ""
    description: OSP URL for API calls
 
resources:
  openstack_project_infra_key:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: $project$-infra_key
          params:
             $project$: { get_param: project_guid }
      save_private_key: true
  Network0_network:
    type: OS::Neutron::Net
    properties:
      name: "Network0"
      shared: false
      value_specs: {"mtu": 1450}
  Network1_network:
    type: OS::Neutron::Net
    properties:
      name: "Network1"
      shared: false
      value_specs: {"mtu": 1450}
  Network0_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network0"
      network_id: { get_resource: Network0_network }
      cidr: "172.25.250.0/24"
      gateway_ip: "172.25.250.1"
      enable_dhcp: "False"
      
      dns_nameservers:
      
        - 8.8.8.8
  Network1_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: "sub-Network1"
      network_id: { get_resource: Network1_network }
      cidr: "192.168.126.0/24"
      gateway_ip: ""
      enable_dhcp: "False"
      
      dns_nameservers:
      
        - 8.8.8.8
  Router0_router:
    type: OS::Neutron::Router
    properties:
      name: "Router0"
      external_gateway_info: { "network": { get_param: public_net_id } }

  
  Router0_Network0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      fixed_ips:
        - ip_address: "172.25.250.1"
  


  
  Router0_Network0_router_if:
    type: OS::Neutron::RouterInterface
    properties:
        router: { get_resource: Router0_router }
        port: { get_resource: Router0_Network0_port }
  
  classroom_services_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: classroom_services_sg
      rules:
      
      - {port_range_max: 22, port_range_min: 22, protocol: tcp, remote_ip_prefix: 0.0.0.0/0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 172.25.250.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 172.25.250.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: tcp, remote_ip_prefix: 192.168.126.0/255.255.255.0}
      
      - {port_range_max: 65535, port_range_min: 1, protocol: udp, remote_ip_prefix: 192.168.126.0/255.255.255.0}
      
  classroom-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:0b:71:97"
      
      security_groups:
        - classroom_services_sg
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "172.25.250.254"}
      
    
    depends_on:
      
      
      - classroom_services_sg
      
    
  classroom-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:41:0c:2d"
      
      #security_groups:
      #  - classroom_services_sg
  
      port_security_enabled: false
          
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.1"}
      
    
    depends_on:
      
      
      - classroom_services_sg
      
    
  worker0-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "8a:3b:bf:2f:f0:6a"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.51"}
      
    
  worker1-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "52:7a:4c:e0:2b:8a"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.52"}
      
    
  lb-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network0_network }
      mac_address: "2c:c2:60:5c:37:11"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network0_subnet}, ip_address: "172.25.250.5"}
      
    
  lb-1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:79:e0:e6"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.5"}
      
    
  master0-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "66:4f:16:3f:5f:0f"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.11"}
      
    
  classroom_server:
    type: OS::Nova::Server
    properties:
      name: "classroom"
      
      image: "cee-cf-111-ARCHIVE-classroom-vda"
      
      config_drive: True
      flavor: m1.medium
      #list_join: ['-', [{ get_param: project_name }, "CPU_2_Memory_4096_Disk_15"]]

      
      key_name:  { get_resource: openstack_project_infra_key }
      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "classroom.example.com"
        
        "hostname": 
          str_replace:
            template: "classroom"
            params:
              REPL: {get_param: project_guid}
        
        
        
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: classroom.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: classroom-0_port}
        
        - port: { get_resource: classroom-1_port}
        
      
    

  
  lb_server:
    type: OS::Nova::Server
    properties:
      name: "lb"
      
      image: "cee-cf-111-ARCHIVE-lb-vda"
      
      config_drive: True
      flavor: PnTAE.m1.medium
      #list_join: ['-', [{ get_param: project_name }, "CPU_1_Memory_2048_Disk_10"]]

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": ""
        
        "hostname": 
          str_replace:
            template: "lb"
            params:
              REPL: {get_param: project_guid}
        
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: lb.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: lb-0_port}
        
        - port: { get_resource: lb-1_port}
        
      
    

  
  master0_server:
    type: OS::Nova::Server
    properties:

      block_device_mapping_v2:
      - boot_index: 0
        device_type: disk
        volume_id:
          get_resource: master0_volume_vda
      - boot_index: 1
        image: rhcos-4.5.6-pntaecommon-iso
        #image: pntae-rhel-7-iso
        delete_on_termination: true
        device_name: hda
        device_type: cdrom
        disk_bus: ide
        volume_size: 2

      name: "master0"
      
      
      config_drive: True
      flavor: PnTAE.m1.xlarge.xdisk.4vCPU
      #list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_16384_Disk_140"]]

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "master0"
        
        "hostname": 
          str_replace:
            template: "master0"
            params:
              REPL: {get_param: project_guid}
        
         
        "cdrom": "rhcos-4.5.6-pntaecommon-iso"
        #"cdrom": "master0_volume_sr0"
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: master0.training1.example.com
          
          params:
            REPL: {get_param: project_guid}
      networks:
        
        - port: { get_resource: master0-0_port}
        
            
  master0_volume_vda:
    properties:
      #image: cee-cf-111-ARCHIVE-master0-vda
      image: pntae-blank-disk-4
      name: master0-vda
      size: 100
    type: OS::Cinder::Volume
      
  
  worker0_server:
    type: OS::Nova::Server
    properties:

      block_device_mapping_v2:
      - boot_index: 0
        device_type: disk
        volume_id:
          get_resource: worker0_volume_vda
      - boot_index: 1
        #image: pntae-rhel-7-iso
        image: rhcos-4.5.6-pntaecommon-iso
        delete_on_termination: true
        device_name: hda
        device_type: cdrom
        disk_bus: ide
        volume_size: 2

      name: "worker0"
      
      
      config_drive: True
      flavor: PnTAE.m1.xlarge.xdisk.4vCPU
      #list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_12288_Disk_140"]]

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "worker0"
        
        "hostname": 
          str_replace:
            template: "worker0"
            params:
              REPL: {get_param: project_guid}
        
         
        #"cdrom": "pntae-rhel-7-iso"
        "cdrom": "rhcos-4.5.6-pntaecommon-iso"
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: worker0.training1.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: worker0-0_port}
        
      
    
  worker0_volume_vda:
    properties:
      image: pntae-blank-disk-4
      name: worker0-vda
      size: 100
    type: OS::Cinder::Volume

  
  worker1_server:
    type: OS::Nova::Server
    properties:

      block_device_mapping_v2:
      - boot_index: 0
        device_type: disk
        volume_id:
          get_resource: worker1_volume_vda
      - boot_index: 1
        #image: pntae-rhel-7-iso
        image: rhcos-4.5.6-pntaecommon-iso
        delete_on_termination: true
        device_name: hda
        device_type: cdrom
        disk_bus: ide
        volume_size: 2


      name: "worker1"
      
      
      config_drive: True
      flavor: PnTAE.m1.xlarge.xdisk.4vCPU
      #list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_12288_Disk_140"]]

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "worker1"
        
        "hostname": 
          str_replace:
            template: "worker1"
            params:
              REPL: {get_param: project_guid}
        
         
        "cdrom": "rhcos-4.5.6-pntaecommon-iso"
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: worker1.training1.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: worker1-0_port}
        
      
  worker1_volume_vda:
    properties:
      image: pntae-blank-disk-4
      name: worker1-vda
      size: 100
    type: OS::Cinder::Volume
    

  bootstrap-0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: Network1_network }
      mac_address: "2c:c2:60:50:52:41"
      
      port_security_enabled: false
      
      
      fixed_ips:
        - {subnet: {get_resource: Network1_subnet}, ip_address: "192.168.126.53"}

  bootstrap_server:
    type: OS::Nova::Server
    properties:

      block_device_mapping_v2:
      - boot_index: 0
        device_type: disk
        volume_id:
          get_resource: bootstrap_volume_vda
      - boot_index: 1
        #image: pntae-rhel-7-iso
        image: rhcos-4.5.6-pntaecommon-iso
        delete_on_termination: true
        device_name: hda
        device_type: cdrom
        disk_bus: ide
        volume_size: 2


      name: "bootstrap"
      
      
      config_drive: True
      flavor: PnTAE.m1.medium
      #list_join: ['-', [{ get_param: project_name }, "CPU_4_Memory_12288_Disk_140"]]

      
      metadata: 
        "guid": { get_param: project_guid }
        "description": "bootstrap"
        
        "hostname": 
          str_replace:
            template: "bootstrap"
            params:
              REPL: {get_param: project_guid}
        
         
        "cdrom": "rhcos-4.5.6-pntaecommon-iso"
         
        
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
          
            #cloud-config
            hostname: bootstrap.training1.example.com
          
          params:
            REPL: {get_param: project_guid}
            
      networks:
        
        - port: { get_resource: bootstrap-0_port}
        
      
  bootstrap_volume_vda:
    properties:
      image: pntae-blank-disk-4
      name: bootstrap-vda
      size: 10
    type: OS::Cinder::Volume

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
    depends_on:
      - classroom_server

  association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: classroom-0_port }


outputs:
  openstack_project_infra_key:
    description: The SSH infra key
    value: {get_attr: [openstack_project_infra_key, private_key]}

